let suggestions = [
    "Anakart Wallpaper",
    "Black Wallpaper",
    "Blue Keyboard Wallpaper",
    "Coding Symbols Wallpaper",
    "Cyber Security Wallpaper",
    "Data Wallpaper",
    "Desktop Wallpaper",
    "Hello World Wallpaper",
    "Html Code Wallpaper",
    "Keyboard Wallpaper",
    "Mackbook Code Wallpaper",
    "Ryzen CPU Wallpaper",
    "Satellite Wallpaper",
    "Server Wallpaper",
    "Windows 10 Wallpaper",
    "",
];